# Generated by Django 2.2.2 on 2019-07-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0003_facturacompra_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacompra',
            name='fecha',
        ),
    ]
