# Generated by Django 2.2.2 on 2019-07-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0004_remove_facturacompra_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'verbose_name': 'Detalle Compra', 'verbose_name_plural': 'Detalles Compras'},
        ),
    ]
