# Generated by Django 2.2.2 on 2019-07-01 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0005_auto_20190701_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
