# Generated by Django 2.2.2 on 2019-07-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0006_facturacompra_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturacompra',
            old_name='fecha',
            new_name='fecha_compra',
        ),
    ]
