# Generated by Django 2.2.2 on 2019-08-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0008_auto_20190718_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='cantidad_inicial',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
