# Generated by Django 2.2.2 on 2019-08-08 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0010_lote_loteventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='loteventa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fac.LoteVenta'),
        ),
    ]
