# Generated by Django 2.2.2 on 2019-09-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0011_auto_20190807_2155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together={('serie', 'numero')},
        ),
    ]
