# Generated by Django 2.2.2 on 2019-09-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0012_auto_20190903_2134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together=set(),
        ),
    ]
