# Generated by Django 2.2.2 on 2019-09-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0013_auto_20190904_1124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together={('serie', 'numero')},
        ),
    ]
