# Generated by Django 2.2.2 on 2019-09-05 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0014_auto_20190904_1211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together=set(),
        ),
    ]
