# Generated by Django 2.2.2 on 2019-09-05 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0015_auto_20190904_1914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together={('serie', 'numero')},
        ),
    ]
