# Generated by Django 2.2.2 on 2019-09-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0016_auto_20190904_1938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together=set(),
        ),
    ]
