# Generated by Django 2.2.2 on 2019-09-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0017_auto_20190904_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='cantidad_producto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
