# Generated by Django 2.2.2 on 2019-09-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0018_auto_20190904_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='serie',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
