# Generated by Django 2.2.2 on 2019-09-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0020_auto_20190904_2237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together={('serie', 'numero')},
        ),
    ]
