# Generated by Django 2.2.2 on 2019-09-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0021_auto_20190905_1123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='facturacompra',
            constraint=models.UniqueConstraint(fields=('serie', 'numero'), name='Restriccion'),
        ),
    ]
