# Generated by Django 2.2.2 on 2019-09-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0022_auto_20190905_1159'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facturacompra',
            name='Restriccion',
        ),
    ]
