# Generated by Django 2.2.2 on 2019-09-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0023_auto_20190905_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cuenta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion_empresa',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
