# Generated by Django 2.2.2 on 2019-09-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0025_auto_20190923_1827'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together={('serie', 'numero')},
        ),
    ]
