# Generated by Django 2.2.2 on 2019-09-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0026_auto_20190923_1933'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together=set(),
        ),
    ]
