# Generated by Django 2.2.2 on 2019-09-27 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0028_registro_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='loteventa',
        ),
        migrations.RemoveField(
            model_name='registro_lote',
            name='loteventa',
        ),
    ]
