# Generated by Django 2.2.2 on 2019-10-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0029_auto_20190926_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='ganancia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_lote',
            name='ganancia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
