# Generated by Django 2.2.2 on 2019-10-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0031_auto_20191007_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_lote',
            name='ganancia',
            field=models.FloatField(),
        ),
    ]
