# Generated by Django 2.2.2 on 2019-08-08 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0006_auto_20190630_2356'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('serie', models.CharField(max_length=45)),
                ('numero', models.IntegerField()),
                ('total', models.FloatField()),
                ('cantidad_producto', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fac.Cliente')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encabezado Venta',
                'verbose_name_plural': 'Encabezado Ventas',
            },
        ),
        migrations.CreateModel(
            name='LoteVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('noLote', models.IntegerField()),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('cantidad_inicial', models.IntegerField()),
                ('costo_unitario', models.FloatField()),
                ('costo_total', models.FloatField()),
                ('facturaventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fac.FacturaVenta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inv.Producto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Venta',
                'verbose_name_plural': 'Detalles Ventas',
            },
        ),
    ]
