# Generated by Django 2.2.2 on 2019-09-07 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fac', '0002_facturaventa_loteventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resoluciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('serie', models.CharField(max_length=45)),
                ('rango_inicial', models.IntegerField()),
                ('numero_resolucion', models.IntegerField()),
                ('fecha_autorizacion', models.DateField()),
                ('correlativo', models.IntegerField()),
                ('rango_final', models.IntegerField()),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolucion',
                'verbose_name_plural': 'Resoluciones',
            },
        ),
    ]
