# Generated by Django 2.2.2 on 2019-09-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_resoluciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='cantidad_producto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facturaventa',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
