# Generated by Django 2.2.2 on 2019-09-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0006_auto_20190630_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=19),
            preserve_default=False,
        ),
    ]
