# Generated by Django 2.2.2 on 2019-09-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0007_producto_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.FloatField(),
        ),
    ]
