# Generated by Django 2.2.2 on 2019-09-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inv', '0008_auto_20190923_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(),
        ),
    ]
